### ISSUE TITLE
Passing "Search Identifier" as a build parameter

### ISSUE THREAD

**Issue by praveendath92** [jenkinsci/git-bisect-plugin#6]
I'm trying to setup a parameterized job which takes all the parameters required for the git-bisect plugin (and some more for downstream project). I could do this without any issues for "Good commit" and "Bad commit but not for "Search Identifier" or "Project to build".

In those cases, when I refer a build parameter as something like $SEARCH_ID it uses this as a literal value rather than taking the value of the environment variable referred by this variable. Could you please fix this?

**Comment by praveendath92** [comment]
Or perhaps there is a way to do what I'm trying to?

**Comment by dorav** [comment]
Are you sure it's working for 'Good commit' and 'Bad commit'? Because these parameters are handled just the same.

This used to work, but I changed the implementation because of [this security issue](https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170). I think this should be supported, but I'd like to hear your use case. I assumed that using the SEARCH_IDENTIFIER will always involve manual intervention, but in your case it might not be so.

**Comment by dorav** [comment]
This should now be solved if you download the latest version. You should be able to supply variables in the standard way of ${VARIABLE_NAME} (notice the brackets)

Please let me know if this works for you as you intended.

**Comment by praveendath92** [comment]
Thanks for fixing this 😃
